title = "My New Hugo Site"
baseURL = "https://aiguamumu.github.io/"
languageCode = "zh-cn"
theme = ["ananke"]
#图片相对路径
uglyurls = true
disablePathToLower = true
#大小写不敏感设置
DefaultContentLanguage = "zh"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
#谷歌分析，分析站点访问
enableRobotsTXT = true
[languages]
  [languages.zh]
    title = "Web_Security"
    weight = 1
    contentDir = "content/Web_Security"
    # languageDirection = 'rtl' for Right-To-Left languages
  [languages.Myself_Explore]
    title = "Myself_Explore"
    weight = 2
    contentDir = "content/Myself_Explore"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
[params]

  featured_image="images/background_1.jpg"
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "月寒日暖，来煎人寿。"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/GoHugoIO"
